feat: update dotfiles

diff --git a/home/madhur/scripts/rofi-power-menu b/home/madhur/scripts/rofi-power-menu
--- a/home/madhur/scripts/rofi-power-menu
+++ b/home/madhur/scripts/rofi-power-menu
@@ -13,37 +13,36 @@ set -e
 set -u
 
 # All supported choices
-#all=(shutdown reboot suspend logout lockscreen)
-all=(shutdown reboot logout)
+all=(shutdown reboot screensaver lockscreen logout)
 
 # By default, show all (i.e., just copy the array)
 show=("${all[@]}")
 
 declare -A texts
 texts[lockscreen]="lock screen"
-# texts[switchuser]="switch user"
 texts[logout]="log out"
-texts[suspend]="suspend"
-# texts[hibernate]="hibernate"
 texts[reboot]="reboot"
 texts[shutdown]="shut down"
+texts[screensaver]="screensaver"
 
 declare -A icons
-icons[lockscreen]="\uf023 "
-# icons[switchuser]="\uf518"
-icons[logout]=" "
-icons[suspend]="\uf9b1 "
-# icons[hibernate]="\uf7c9"
-icons[reboot]=" "
-icons[shutdown]=" "
-icons[cancel]=" "
+#icons[lockscreen]="system-lock-screen-symbolic"
+icons[lockscreen]="<span color='yellow'></span>"
+icons[logout]="<span color='magenta'></span>"
+icons[screensaver]="<span color='green'>󰹑</span>"
+icons[reboot]="<span color='orange'>勒</span>"
+#icons[logout]="system-switch-user-symbolic"
+#icons[logout]="system-switch-user-symbolic"
+#icons[reboot]="system-reboot-symbolic"
+#icons[shutdown]="system-shutdown-symbolic"
+icons[shutdown]="<span color='red'>⏻</span>"
+#icons[screensaver]="preferences-desktop-screensaver-symbolic"
+icons[cancel]="<U+F467> "
 
 declare -A actions
-actions[lockscreen]="rofi-lock"
-#actions[switchuser]="???"
+actions[lockscreen]="lockscreen.sh"
+actions[screensaver]="screensaver.sh"
 actions[logout]="pkill -KILL -u $USER"
-actions[suspend]="rofi-suspend"
-# actions[hibernate]="systemctl hibernate"
 actions[reboot]="systemctl reboot"
 actions[shutdown]="systemctl poweroff"
 
@@ -52,7 +51,8 @@ confirmations=()
 
 # By default, no dry run
 dryrun=false
-showsymbols=true
+showsymbols=false
+showtext=true
 
 function check_valid {
     option="$1"
@@ -68,7 +68,7 @@ function check_valid {
 }
 
 # Parse command-line options
-parsed=$(getopt --options=h --longoptions=help,dry-run,confirm:,choices:,choose:,symbols,no-symbols --name "$0" -- "$@")
+parsed=$(getopt --options=h --longoptions=help,dry-run,confirm:,choices:,choose:,symbols,no-symbols,text,no-text,symbols-font: --name "$0" -- "$@")
 if [ $? -ne 0 ]; then
     echo 'Terminating...' >&2
     exit 1
@@ -88,26 +88,31 @@ while true; do
             echo "  rofi -show menu -modi \"menu:rofi-power-menu --choices=shutdown/reboot\""
             echo
             echo "Available options:"
-            echo "  --dry-run          Don't perform the selected action but print it to stderr."
-            echo "  --choices CHOICES  Show only the selected choices in the given order. Use / "
-            echo "                     as the separator. Available choices are lockscreen, logout,"
-            echo "                     suspend, hibernate, reboot and shutdown. By default, all"
-            echo "                     available choices are shown."
-            echo "  --confirm CHOICES  Require confirmation for the gives choices only. Use / as"
-            echo "                     the separator. Available choices are lockscreen, logout,"
-            echo "                     suspend, hibernate, reboot and shutdown. By default, only"
-            echo "                     irreversible actions logout, reboot and shutdown require"
-            echo "                     confirmation."
-            echo "  --choose CHOICE    Preselect the given choice and only ask for a confirmation"
-            echo "                     (if confirmation is set to be requested). It is strongly"
-            echo "                     recommended to combine this option with --confirm=CHOICE"
-            echo "                     if the choice wouldn't require confirmation by default."
-            echo "                     Available choices are lockscreen, logout, suspend,"
-            echo "                     hibernate, reboot and shutdown."
-            echo "  --[no-]symbols     Show Unicode symbols or not. Requires a font with support"
-            echo "                     for the symbols. Use, for instance, fonts from the"
-            echo "                     Nerdfonts collection. By default, they are shown"
-            echo "  -h,--help          Show this help text."
+            echo "  --dry-run            Don't perform the selected action but print it to stderr."
+            echo "  --choices CHOICES    Show only the selected choices in the given order. Use /"
+            echo "                       as the separator. Available choices are lockscreen,"
+            echo "                       logout,suspend, hibernate, reboot and shutdown. By"
+            echo "                       default, all available choices are shown."
+            echo "  --confirm CHOICES    Require confirmation for the gives choices only. Use / as"
+            echo "                       the separator. Available choices are lockscreen, logout,"
+            echo "                       suspend, hibernate, reboot and shutdown. By default, only"
+            echo "                       irreversible actions logout, reboot and shutdown require"
+            echo "                       confirmation."
+            echo "  --choose CHOICE      Preselect the given choice and only ask for a"
+            echo "                       confirmation (if confirmation is set to be requested). It"
+            echo "                       is strongly recommended to combine this option with"
+            echo "                       --confirm=CHOICE if the choice wouldn't require"
+            echo "                       confirmation by default. Available choices are"
+            echo "                       lockscreen, logout, suspend, hibernate, reboot and"
+            echo "                       shutdown."
+            echo "  --[no-]symbols       Show Unicode symbols or not. Requires a font with support"
+            echo "                       for the symbols. Use, for instance, fonts from the"
+            echo "                       Nerdfonts collection. By default, they are shown"
+            echo "  --[no-]text          Show text description or not."
+            echo "  --symbols-font FONT  Use the given font for symbols. By default, the symbols"
+            echo "                       use the same font as the text. That font is configured"
+            echo "                       with rofi."
+            echo "  -h,--help            Show this help text."
             exit 0
             ;;
         "--dry-run")
@@ -138,6 +143,18 @@ while true; do
             showsymbols=false
             shift 1
             ;;
+        "--text")
+            showtext=true
+            shift 1
+            ;;
+        "--no-text")
+            showtext=false
+            shift 1
+            ;;
+        "--symbols-font")
+            symbols_font="$2"
+            shift 2
+            ;;
         "--")
             shift
             break
@@ -149,15 +166,31 @@ while true; do
     esac
 done
 
+if [ "$showsymbols" = "false" -a "$showtext" = "false" ]
+then
+    echo "Invalid options: cannot have --no-symbols and --no-text enabled at the same time." >&2
+    exit 1
+fi
+
 # Define the messages after parsing the CLI options so that it is possible to
 # configure them in the future.
 
 function write_message {
-    icon="<span font_size=\"medium\">$1</span>"
+    if [ -z ${symbols_font+x} ];
+    then
+        icon="<span font_size=\"medium\">$1</span>"
+    else
+        icon="<span font=\"${symbols_font}\" font_size=\"medium\">$1</span>"
+    fi
     text="<span font_size=\"medium\">$2</span>"
     if [ "$showsymbols" = "true" ]
     then
-        echo -n "\u200e$icon \u2068$text\u2069"
+        if [ "$showtext" = "true" ]
+        then
+            echo -n "\u200e$icon \u2068$text\u2069"
+        else
+            echo -n "\u200e$icon"
+        fi
     else
         echo -n "$text"
     fi
@@ -198,10 +231,10 @@ echo -e "\0markup-rows\x1ftrue"
 
 if [ -z "${selection+x}" ]
 then
-    echo -e "\0prompt\x1f"
+    echo -e "\0prompt\x1fPower menu"
     for entry in "${show[@]}"
     do
-        echo -e "${messages[$entry]}\0icon\x1f${icons[$entry]}"
+        echo -en "${messages[$entry]}\0icon\x1f${icons[$entry]}\n"
     done
 else
     for entry in "${show[@]}"
@@ -214,7 +247,7 @@ else
                 if [ "$entry" = "$confirmation" ]
                 then
                     # Ask for confirmation
-                    echo -e "\0prompt\x1fAre you sure?"
+                    echo -e "\0prompt\x1fAre you sure"
                     echo -e "${confirmationMessages[$entry]}\0icon\x1f${icons[$entry]}"
                     echo -e "${confirmationMessages[cancel]}\0icon\x1f${icons[cancel]}"
                     exit 0
@@ -245,4 +278,3 @@ else
     echo "Invalid selection: $selection" >&2
     exit 1
 fi
-
